[Backend]
toolbar_new		= "новий"
toolbar_details		= "Подробности"
toolbar_save		= "зберегти"
toolbar_delete		= "видалити"
toolbar_edit		= "редагувати"
toolbar_filter		= "фільтр"
TOOLBAR_GO_BACK = "Назад"
TOOLBAR_TOP		= "Вверх"
TOOLBAR_DOWN	= "Вниз"
TOOLBAR_DOLINK	= "Привязать"
TOOLBAR_APPROVE	= "Подтвердить"
ERR_INVALID_LOGIN = "Неверный логин или пароль"

menu_logout			= "Вихід"

backend_nick_alreadytaken = "Sorry. this nick is already taken"
backend_email_alreadytaken = "Sorry. this email is already used"

date_day			= "Day"
date_month		= "Month"
date_year			= "Year"

html_select_empty	= "- Choose -"

textbox_error		= "Помилки"
textbox_message	= "Повідомлення"

BEND_MENU_WARNING = "Внимание, в меню будут отображаться только 2 уровня вложенности"


;err_invalid_login			= "Неправильний логін/пароль"
err_field_required			= "Поле '%%field%%' є обов'язковим"
err_all_fields_required		= "Заповніть усі поля"

SETTINGS_BREADCRUMP = ""

FIELD_EMPTY = "Поле не може бути порожнім"
FIELD_INCORRECT = "Некоректне значення поля"