[Backend]

; --- settings ---
settings_create		= "Создать новую настройку"
settings_breadcrump	= "Настройки"
settings_exists		= "Такая настройка уже существует"

; --- users ---
users_breadcrump	= "Пользователи"
users_extra_info	= "Доп. информация"

; --- static pages ---
pages_breadcrump	= "Статические страницы"
pages_exists		= "Страница с таким адресом уже существует"
pages_create		= "Создать новую статическую страницу"


[PAGINATION]
PAGIN_NEXT = "вперед&gt;"
PAGIN_PREV = "&lt;назад"

[ALL]
IMG_INCORRCT_TYPE = "Неподдерживаемый тип файла"
IMG_INCORRECT_WIDTH = "Ширина фотографии не может быть меньше "
IMG_INCORRECT_SIZE = "Размеры фотографии не могут быть меньше "

YES_CONST = "так";
NO_CONST = "ні";
