[SCRIPT SETTINGS]
PROFILE_MIN_PWD_LENGTH = 3;
FORGOT_TMP_PASS_LENGTH = 8;


[ERR]
PROFILE_EMAIL_INCORRECT = "Некорректный Email"
PROFILE_PWD_CONFIRM_NOT_EQUAL = "Пароль и подтверждение не совпадают"
PROFILE_EMAIL_BUSY = "Этот E-mail уже используется"
PROFILE_CAPTCHA_WRONG = "Неправильный Защитный код"
PROFILE_CREDENTIALS_INVALID = "Неправильный email или пароль";
PROFILE_FORGOT_EMAIL_EMPTY = "Поле Email не может быть пустым"
PROFILE_FORGOT_NO_USER = "Пользователя с таким email адресом не существует"
PROFILE_CURRENT_PASSWORD_WRONG = "Неправильный текущий пароль"

SUBSCR_EMAIL_BUSY = "Ваш email уже существует в системе, попробуйте <a href='/user/login.html'>авторизоваться</a> или <a href="/user/forgot.html">восстановить пароль</a>"