<?php
    echo "<h2>Not implemented  </h2>\n"; exit;



    //$this->DB->Delete($this->ids, "", "id_order");
//    $orderObj = new EkvRoomEventOrder();
//
//    foreach($this->ids as $base_order_id){
//        $base_order_info = $orderObj->getBaseOrderInfo($base_order_id);
//        //pa($base_order_info);
//
//        //--- oreder can be deleted only if it doesnt have status already payed ---//
//        if( !empty($base_order_info) && $base_order_info["order_status"] != EkvRoomHelper::ORDER_STATUS_SUCCEED ){
//            //--- free cells ---//
//            $orderObj->setExtraOrderCellsStatus($base_order_id, EkvRoomHelper::CELL_STATUS_FREE);
//
//            //--- order full delete ---//
//            $orderObj->deleteOrderCompletely($base_order_id);
//        }
//    }
//
// 	$this->ChangeLocation('base_browse');

?>
