<?php
/**
 * ============================================================
 * File name: xxx.xxx
 *      Date: xx/xx/2009
 *   Purpose: 
 * ============================================================
 */
	return array(
				0 => array(
						'id' => 0,
						'title' => 'Menu',
						'module' => 'base',
						'entity' => 'menu',
						'action' => 'browse',
					),
				1 => array(
						'id' => 1,
						'title' => 'Users',
						'module' => 'base',
						'entity' => 'user',
						'action' => 'browse',
					),
				2 => array(
						'id' => 2,
						'title' => 'Logout',
						'module' => 'base',
						'entity' => 'user',
						'action' => 'logout',
					),
				);

?>
